# 存储配置
store:
  engine: pebble
  path: ./db/2/

# server 相关
server:
  # grpc 配置
  grpc_port: 10002
  # http 配置
  http_port: 11002
  # 限流容量，每秒的 qps 限制
  rate: 30000
  # 慢请求的阈值，单位为 ms
  slow_query_threshold: 100

# 集群相关
cluster:
  # node_id，不能重复，得唯一
  node_id: 3
  # raft 协议提交的日志存储位置
  path: ./cluster/
  # 通信的端口
  port: 12002
  # 提交超时时间，单位为 ms
  time_out: 1000
  # 集群 master 地址
  master: 127.0.0.1:11000